import { Fragment, useEffect, useState } from 'react';
import { format } from 'date-fns';
import { ChevronDown, ChevronRight, Database, IndianRupee, Sparkles, Volume2 } from 'lucide-react';
import apiClient from '../services/apiClient';
import { CostAuditConversation, CostAuditResponse } from '../types/api';

const money = (value: number) => `₹${value.toFixed(4)}`;
const sourceLabel = (operation: string, source: string) => {
  if (operation === 'tts') return source === 'cache' ? 'Audio from TTS cache' : 'Audio generated by TTS';
  if (operation === 'stt') return 'Audio transcribed by STT';
  if (source === 'cache') return 'Answer from QA cache';
  if (source === 'llm') return 'Answer generated by LLM';
  return 'Answer from local rules';
};

function ConversationDetails({ item }: { item: CostAuditConversation }) {
  return <div className="space-y-5 p-5 bg-foreground/[.025]">
    <section><h3 className="font-semibold mb-2">Complete conversation</h3>
      <div className="audit-transcript">{item.messages.map(message =>
        <div key={message.id} className={message.role}><div><span>{message.role === 'user' ? 'Passenger' : 'Metro AI'} · Message #{message.id}</span><p>{message.content}</p><time>{format(new Date(message.created_at), 'dd/MM/yy HH:mm:ss')}</time></div></div>)}</div>
    </section>
    <section><h3 className="font-semibold mb-2">Generation and cost timeline</h3>
      <div className="space-y-2">{item.events.map(event => <div key={event.id} className="rounded-lg border border-foreground/10 bg-background p-4">
        <div className="flex flex-wrap items-center gap-2"><strong>{sourceLabel(event.operation, event.source)}</strong><span className="text-xs text-foreground/50">{event.provider} · {event.model}</span><time className="ml-auto text-xs text-foreground/50">{format(new Date(event.created_at), 'HH:mm:ss')}</time></div>
        {event.operation !== 'stt' && <><p className="mt-2"><span className="text-foreground/50">Input:</span> {event.question}</p>{event.answer && <p className="mt-1"><span className="text-foreground/50">Answer:</span> {event.answer}</p>}</>}
        <div className="mt-2 flex gap-4 text-xs"><span>Actual {money(event.actual_cost_inr)}</span><span>Without cache {money(event.uncached_cost_inr)}</span><span className="text-emerald-500">Saved {money(event.saved_cost_inr)}</span></div>
      </div>)}</div>
    </section>
  </div>;
}

export default function CostAuditPage() {
  const [data, setData] = useState<CostAuditResponse | null>(null);
  const [channel, setChannel] = useState(''); const [source, setSource] = useState('');
  const [page, setPage] = useState(1); const [openId, setOpenId] = useState<number | null>(null);
  useEffect(() => { const params = new URLSearchParams({ page: String(page), page_size: '25' });
    if (channel) params.set('channel', channel); if (source) params.set('source', source);
    apiClient.get<CostAuditResponse>(`/cost-audit?${params}`).then(r => setData(r.data));
  }, [channel, source, page]);
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">AI cost & cache audit</h1><p className="text-sm text-foreground/60">One row per interaction. Open it to see the full conversation, answer source, audio source, cost, and cache saving.</p></div>
    {data && <><div className="grid gap-4 md:grid-cols-4">{[
      ['Actual provider cost', money(data.summary.actual_cost_inr), IndianRupee], ['Cost without cache', money(data.summary.uncached_cost_inr), Sparkles],
      ['Saved by cache', money(data.summary.saved_cost_inr), Database], ['Call STT cost', money(data.summary.stt_cost_inr), Volume2],
    ].map(([label,value,Icon]: any) => <div className="dashboard-card p-5" key={label}><Icon className="h-5 w-5 text-primary"/><p className="mt-3 text-xs text-foreground/60">{label}</p><strong className="text-xl">{value}</strong></div>)}</div>
    <section className="dashboard-card p-5">
      <div className="mb-4"><h2 className="font-semibold">TTS cache summary</h2><p className="text-xs text-foreground/60">Lifetime synthesized-audio storage, reuse, and Sarvam TTS savings.</p></div>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <div className="rounded-lg border border-foreground/10 p-4"><p className="text-xs text-foreground/60">Stored audio entries</p><strong className="mt-1 block text-xl">{data.tts_cache.stored_entries}</strong></div>
        <div className="rounded-lg border border-foreground/10 p-4"><p className="text-xs text-foreground/60">Audio cache reuses</p><strong className="mt-1 block text-xl">{data.tts_cache.total_reuses}</strong></div>
        <div className="rounded-lg border border-foreground/10 p-4"><p className="text-xs text-foreground/60">TTS-only savings</p><strong className="mt-1 block text-xl text-emerald-500">{money(data.tts_cache.saved_cost_inr)}</strong></div>
        <div className="rounded-lg border border-foreground/10 p-4"><p className="text-xs text-foreground/60">Most reused audio</p>{data.tts_cache.most_reused ? <><strong className="mt-1 block text-xl">{data.tts_cache.most_reused.reuse_count} times</strong><p className="mt-1 line-clamp-2 text-xs text-foreground/60" title={data.tts_cache.most_reused.text}>{data.tts_cache.most_reused.text}</p><p className="mt-1 text-xs uppercase text-foreground/40">{data.tts_cache.most_reused.language}</p></> : <strong className="mt-1 block text-xl">—</strong>}</div>
      </div>
    </section>
    <div className="dashboard-card p-4 flex flex-wrap gap-3"><select value={channel} onChange={e=>{setChannel(e.target.value);setPage(1)}} className="form-input"><option value="">All channels</option><option value="chat">Chat</option><option value="call">Voice call</option></select><select value={source} onChange={e=>{setSource(e.target.value);setPage(1)}} className="form-input"><option value="">All sources</option><option value="cache">Any cache hit</option><option value="llm">LLM used</option><option value="tts">Fresh TTS used</option><option value="rules">Local rules used</option></select></div>
    <div className="dashboard-card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3"></th><th className="p-3">Interaction</th><th className="p-3">Passenger</th><th className="p-3">Sources used</th><th className="p-3 text-right">Actual</th><th className="p-3 text-right">Saved</th></tr></thead><tbody>{data.items.map(item => <Fragment key={item.conversation_id}>
      <tr key={item.conversation_id} className="border-b border-foreground/10 cursor-pointer hover:bg-foreground/5" onClick={()=>setOpenId(openId===item.conversation_id?null:item.conversation_id)}><td className="p-3">{openId===item.conversation_id?<ChevronDown className="h-4 w-4"/>:<ChevronRight className="h-4 w-4"/>}</td><td className="p-3">{item.channel==='call'?'Voice call':'Chat'} #{item.conversation_id}<div className="text-xs text-foreground/50">{format(new Date(item.created_at),'dd/MM/yy HH:mm')} · {item.status}</div></td><td className="p-3">{item.user_name||item.user_number}</td><td className="p-3"><div>LLM {item.llm_calls} · QA cache {item.cache_hits}</div>{item.channel==='call'&&<div className="text-xs text-foreground/50">Fresh TTS {item.fresh_tts} · Cached audio {item.cached_tts}</div>}</td><td className="p-3 text-right">{money(item.actual_cost_inr)}</td><td className="p-3 text-right text-emerald-500">{money(item.saved_cost_inr)}</td></tr>
      {openId===item.conversation_id&&<tr><td colSpan={6} className="p-0"><ConversationDetails item={item}/></td></tr>}</Fragment>)}</tbody></table></div></div>
    <div className="flex justify-end gap-2"><button disabled={page===1} onClick={()=>setPage(p=>p-1)} className="secondary-button">Previous</button><button disabled={page*25>=data.total} onClick={()=>setPage(p=>p+1)} className="secondary-button">Next</button></div></>}
  </div>;
}
